---
version: '3.8'

networks:
  mynetwork:
    name: "${APP_NAME}-net"

services:
  php:
    container_name: "${APP_NAME}-php"
    labels:
      local.project: "${APP_NAME}"
    restart: always
    ports:
      - "${API_LISTEN_PORT}:80"
    volumes:
      - "${APP_FOLDER}:/var/www/html"
      - ./apache/vhosts:/etc/apache2/sites-enabled
      - ./apache/logs:/var/log/apache2:cached
      - ./tmp:/tmp
    environment:
      serverMail: "localhost"
    networks:
      - mynetwork

  mariadb:
    container_name: "${APP_NAME}-mariadb"
    labels:
      local.project: "${APP_NAME}"
    image: mariadb
    restart: always
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb:/etc/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_USER_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$${MARIADB_ROOT_PASSWORD}
      interval: 5s
      retries: 5
    networks:
      - mynetwork

  adminer:
    container_name: "${APP_NAME}-adminer"
    labels:
      local.project: "${APP_NAME}"
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'dracula'
      ADMINER_PLUGINS: 'tables-filter tinymce'
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - php
    networks:
      - mynetwork

volumes:
  db_data:
